[build]
  base = "frontend/campoenorden_frontend"
  command = "npm install && npm run build"
  publish = "frontend/campoenorden_frontend/www"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
