# Generated by Django 6.0.4 on 2026-04-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_aplicacion', models.CharField(max_length=100)),
                ('insumos', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='core.lote')),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labores',
                'ordering': ['-fecha'],
            },
        ),
    ]
