# Generated by Django 6.0.5 on 2026-05-09 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipolaborpersonalizado_campo_localidad_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.persona'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permisos_especiales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN_PRINCIPAL', 'Admin Principal'), ('ADMIN_EMPRESA', 'Admin de Empresa'), ('OPERARIO', 'Operario'), ('CONSULTA', 'Usuario de Consulta'), ('PRODUCTOR', 'Cliente / Productor')], default='OPERARIO', max_length=50),
        ),
    ]
