# Generated by Django 6.0.8 on 2026-09-10 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_data'),
        ('users', '0004_user_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('MATRICULA', 'Matrícula'), ('MENSUALIDAD', 'Mensualidad'), ('SERVICIO', 'Servicio especial'), ('OTRO', 'Otro')], default='MENSUALIDAD', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PENDIENTE', 'Pendiente'), ('ANULADO', 'Anulado')], default='RECIBIDO', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_plataforma', to='core.persona')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago a CampoEnOrden',
                'verbose_name_plural': 'Pagos a CampoEnOrden',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=30, null=True)),
                ('target_id', models.CharField(blank=True, max_length=50, null=True)),
                ('target_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_actor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de acción',
                'verbose_name_plural': 'Bitácoras de acciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
