# Generated by Django 6.0.8 on 2026-09-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_persona_empresa'),
        ('users', '0005_pago_userauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_user', to='core.persona'),
        ),
    ]
