# Generated by Django 6.0.4 on 2026-04-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cpe', models.CharField(max_length=50, unique=True, verbose_name='Número de CPE')),
                ('ctg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Trazabilidad Geográfica')),
                ('patente_camion', models.CharField(max_length=10, verbose_name='Patente Camión')),
                ('patente_acoplado', models.CharField(blank=True, max_length=10, null=True, verbose_name='Patente Acoplado')),
                ('chofer', models.CharField(max_length=100)),
                ('peso_origen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_destino', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flete',
                'verbose_name_plural': 'Fletes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
