# Generated by Django 6.0.4 on 2026-04-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('superficie_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cultivo_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.campo')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'unique_together': {('campo', 'nombre')},
            },
        ),
    ]
