# Generated by Django 6.0.5 on 2026-05-09 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLaborPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de labor personalizado',
                'verbose_name_plural': 'Tipos de labor personalizados',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='campo',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_productor', to='core.persona'),
        ),
        migrations.AddField(
            model_name='campo',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labor',
            name='cargada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores_cargadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labor',
            name='estado',
            field=models.CharField(choices=[('CARGADA', 'Cargada'), ('PENDIENTE_REVISION', 'Pendiente de revisión'), ('REVISADA', 'Revisada'), ('APROBADA', 'Aprobada'), ('PENDIENTE_FACTURA', 'Pendiente de facturar'), ('FACTURADA', 'Facturada'), ('COBRADA', 'Cobrada')], default='CARGADA', max_length=30),
        ),
        migrations.AddField(
            model_name='labor',
            name='fecha_hora_carga',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labor',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labor',
            name='foto_receta',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
        migrations.AddField(
            model_name='labor',
            name='moneda',
            field=models.CharField(blank=True, default='USD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='labor',
            name='precio_por_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='labor',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores_responsable', to='core.persona'),
        ),
        migrations.AddField(
            model_name='labor',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborinsumo',
            name='dosis_calculada',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(choices=[('HERBICIDA', 'Herbicida'), ('FERTILIZANTE', 'Fertilizante'), ('FUNGICIDA', 'Fungicida'), ('INSECTICIDA', 'Insecticida'), ('SEMILLA', 'Semilla'), ('COADYUVANTE', 'Coadyuvante / Aceite'), ('INOCULANTE', 'Inoculante'), ('SERVICIO', 'Servicio'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='labor',
            name='tipo',
            field=models.CharField(choices=[('SIEMBRA', 'Siembra'), ('PULVERIZACION_TERRESTRE', 'Pulverización terrestre'), ('PULVERIZACION_DRONES', 'Pulverización con drones'), ('PULVERIZACION_AEREA', 'Pulverización aérea'), ('FERTILIZACION_TERRESTRE', 'Fertilización terrestre'), ('FERTILIZACION_DRONES', 'Fertilización con drones'), ('COSECHA', 'Cosecha'), ('OTRA', 'Otra')], max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(blank=True, choices=[('DUENO', 'Dueño / Locador'), ('ARRENDATARIO', 'Arrendatario / Locatario'), ('CONTRATISTA', 'Contratista'), ('CHOFER', 'Chofer'), ('ADMINISTRADOR', 'Administrador'), ('RESPONSABLE_CARGA', 'Responsable de Carga'), ('BENEFICIARIO', 'Beneficiario de Pagos'), ('PRODUCTOR', 'Productor')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('PERSONA', 'Persona Física'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('fecha_precio', models.DateField()),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='core.insumo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_proveedor', to='core.persona')),
            ],
            options={
                'verbose_name': 'Precio de Producto',
                'verbose_name_plural': 'Precios de Productos',
                'ordering': ['-fecha_precio'],
            },
        ),
        migrations.AddField(
            model_name='laborinsumo',
            name='precio_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores_insumo', to='core.productoprecio'),
        ),
        migrations.AddField(
            model_name='labor',
            name='sub_tipo_otra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores', to='core.tipolaborpersonalizado'),
        ),
    ]
