# Generated by Django 6.0.8 on 2026-09-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_empresa', to='core.persona'),
        ),
    ]
