# Generated by Django 6.0.5 on 2026-09-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_persona_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lote',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
